import type { Metadata } from "next"
import "@hippods/react-components-layout/style.css"
import "@hippods/react-components-interactive/style.css"
import "@hippods/themes/themes.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
