import "@/shared/styles"
import type { Metadata } from "next"
import { ThemeScript } from "@/shared/components/ThemeScript"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning>
        <ThemeScript />
        {children}
      </body>
    </html>
  )
}
